export const typography = {
	h1: {
		fontFamily: "Inter, Arial, sans-serif",
		fontWeight: 400,
		fontSize: "57px",
		lineHeight: "64px",
		letterSpacing: "0px",
	},
	h2: {
		fontFamily: "Inter, Arial, sans-serif",
		fontWeight: 400,
		fontSize: "45px",
		lineHeight: "52px",
		letterSpacing: "0px",
	},
	h3: {
		fontFamily: "Inter, Arial, sans-serif",
		fontWeight: 400,
		fontSize: "36px",
		lineHeight: "44px",
		letterSpacing: "0px",
	},
	h4: {
		fontFamily: "Inter, Arial, sans-serif",
		fontWeight: 400,
		fontSize: "32px",
		lineHeight: "40px",
		letterSpacing: "0px",
	},
	h5: {
		fontFamily: "Inter, Arial, sans-serif",
		fontWeight: 400,
		fontSize: "28px",
		lineHeight: "36px",
		letterSpacing: "0px",
	},
	h6: {
		fontFamily: "Inter, Arial, sans-serif",
		fontWeight: 400,
		fontSize: "24px",
		lineHeight: "32px",
		letterSpacing: "0px",
	},
	subtitle1: {
		fontFamily: "Inter, Arial, sans-serif",
		fontWeight: 400,
		fontSize: "16px",
		lineHeight: "24px",
		letterSpacing: "0px",
	},
	subtitle2: {
		fontFamily: "Inter, Arial, sans-serif",
		fontWeight: 400,
		fontSize: "14px",
		lineHeight: "20px",
		letterSpacing: "0px",
	},
	body1: {
		fontFamily: "Inter, Arial, sans-serif",
		fontWeight: 400,
		fontSize: "14px",
		lineHeight: "16px",
		letterSpacing: "0px",
	},
	body2: {
		fontFamily: "Inter, Arial, sans-serif",
		fontWeight: 500,
		fontSize: "14px",
		lineHeight: "20px",
		letterSpacing: "0px",
	},
	button: {
		fontFamily: "Inter, Arial, sans-serif",
		fontWeight: 500,
		fontSize: "16px",
		lineHeight: "24px",
		letterSpacing: "0px",
	},
	caption: {
		fontFamily: "Inter, Arial, sans-serif",
		fontWeight: 500,
		fontSize: "12px",
		lineHeight: "16px",
		letterSpacing: "0px",
	},
	overline: {
		fontFamily: "Inter, Arial, sans-serif",
		fontWeight: 500,
		fontSize: "11px",
		lineHeight: "16px",
		letterSpacing: "0px",
	},
}
