import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import NavBar from '@/app/components/NavBar';
import { ReactNode } from 'react';
import ThemeRegistry from '@/app/components/ThemeRegistry';
import Footer from '@/app/components/Footer';

const inter = Inter({
  weight: ['400', '500', '600'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en' className={inter.className}>
      <ThemeRegistry options={{ key: 'mui' }}>
        <body>
          <NavBar />
          <main className={'mx-auto my-44 max-w-7xl'}>{children}</main>
          <Footer />
        </body>
      </ThemeRegistry>
    </html>
  );
}
